name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3  

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build the Docker images
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/fastliosc:$(date +%s)
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/fastlio:latest
